keyring:
  dataset:
    cifar10: datasets/cifar10.yaml
    fashion_mnist: datasets/fashion_mnist.yaml
  model:
    gan: models/gan.yaml
    diffusion: models/diffusion.yaml

?debug: false
epochs: 2000
batch_size: 128
arch: diff

datasets:
- cifar10
# - fashion_mnist

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0005

# --- Logging ---
# logger: mlflow
# logger: tensorboard
logger: wandb
logdir: logs

checkpoint_dir: checkpoints/
run_name: diff_test
# experiment: gans
experiment: diff

# This is the metric to optimize
# dev_metric: dev_generator_loss # for GANs
dev_metric: dev_loss # for diff
