keyring:
  dataset:
    cifar10: datasets/cifar10.yaml
    fashion_mnist: datasets/fashion_mnist.yaml
  model:
    gan: models/gan.yaml
    # diffusion: null

?debug: false
epochs: 20
batch_size: 128
arch: gan

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.001

# logger: mlflow
# logger: tensorboard
logger: wandb
logdir: logs

# MLFlow Stuff
checkpoint_dir: checkpoints/
run_name: first_go
experiment: gans

# This is the metric to optimize
dev_metric: dev_loss
