keyring:
  dataset:
    cifar10: datasets/cifar10.yaml
    fashion_mnist: datasets/fashion_mnist.yaml
  model:
    gan: models/gan.yaml
    # diffusion: null

?debug: false
epochs: 2000
batch_size: 128
arch: gan

datasets:
- cifar10
# - fashion_mnist

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0005

# logger: mlflow
# logger: tensorboard
logger: wandb
logdir: logs

# MLFlow Stuff
checkpoint_dir: checkpoints/
run_name: fashion_only
experiment: gans

# This is the metric to optimize
dev_metric: dev_generator_loss
